/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121831-gd3e80837e7-20251123"
#endif /* AVUTIL_FFVERSION_H */
